import {
  getChatSummaries,
  saveChat,
  getChatById,
  deleteChatById,
} from '../services/chatHistoryService.js';

/**
 * Retrieves all chat sessions with pagination support.
 * Accepts `page` and `limit` as query parameters.
 * @param {express.Request} req - The request object.
 * @param {express.Response} res - The response object.
 * @param {express.NextFunction} next - The next middleware function.
 */
export async function getChats(req, res, next) {
  try {
    const page = parseInt(req.query.page) || 1;
    const limit = parseInt(req.query.limit) || 8;
    
    const result = await getChatSummaries(page, limit);
    res.status(200).json(result);
  } catch (error) {
    next(error);
  }
}

/**
 * Retrieves a specific chat session by ID.
 * @param {express.Request} req - The request object.
 * @param {express.Response} res - The response object.
 * @param {express.NextFunction} next - The next middleware function.
 */
export async function getSingleChat(req, res, next) {
  try {
    const { chatId } = req.params;
    
    // Service will throw a 404 error if not found, 
    // which catches below and goes to global handler.
    const chat = await getChatById(chatId);
    
    res.status(200).json(chat);
  } catch (error) {
    next(error);
  }
}

/**
 * Creates a new chat session.
 * Expects `title`, `personaName`, `messages`, `dialogueTree`, and `mode` in the request body.
 * @param {express.Request} req - The request object.
 * @param {express.Response} res - The response object.
 * @param {express.NextFunction} next - The next middleware function.
 */
export async function createChat(req, res, next) {
  try {
    const { title, personaName, messages, dialogueTree, mode } = req.body;

    // Validation (Keep basic input validation in Controller)
    if (!personaName || !messages) {
      return res.status(400).json({ error: 'PersonaName and messages are required.' });
    }

    // Delegate Logic to Service (Service generates ID and Date)
    const newChatId = await saveChat({
      title,
      personaName,
      messages,
      dialogueTree,
      mode,
    });

    // Return the ID generated by the service
    res.status(201).json({
      message: 'Chat saved successfully',
      chatId: newChatId,
    });
  } catch (error) {
    next(error);
  }
}

/**
 * Deletes a chat session by ID.
 * @param {express.Request} req - The request object.
 * @param {express.Response} res - The response object.
 * @param {express.NextFunction} next - The next middleware function.
 */
export async function deleteChat(req, res, next) {
  try {
    const { chatId } = req.params;

    // Service returns boolean or throws error
    const isDeleted = await deleteChatById(chatId);

    if (isDeleted) {
      res.status(200).json({ message: 'Chat deleted successfully' });
    } else {
      // If service didn't throw but returned false
      res.status(404).json({ message: 'Chat not found' });
    }
  } catch (error) {
    next(error);
  }
}
